### ISSUE TITLE
Get request on “Find similar”

### ISSUE THREAD

**Issue by HappyUnknown** [Shiroechi/BooruDex#41]
Hi there. I am trying to make Booru desktop tool for finding similar images and getting their links (like they did it on yandere). Yesterday I looked through the functions of your library, but haven’t seen something alike. Is there any way I have access to this functionality, or it’s a tool for the websites’ developers use only. Thanks in advance.

**Comment by Shiroechi** [comment]
@HappyUnknown , hi there, sorry for late reply.

If you mean "Find similar" image is from this [link](https://yande.re/post/similar), then it is a website tool. Unfortunately there's no API for "Find Similar". So I can't implement it into the library.
